package com.kuilunfuzhe.monvhua.renderer.activity;

import com.kuilunfuzhe.monvhua.features.activity.UiActivityBubbleStyle;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.texture.NativeImage;
import net.minecraft.client.texture.NativeImageBackedTexture;
import net.minecraft.util.Identifier;

/**
 * Small transparent preview textures for the configuration screen. The world
 * bubble is generated by a GPU shader, so the editor uses the same shape math
 * rasterized once instead of painting an opaque rectangle.
 */
public final class UiActivityBubblePreviewTexture {
    private static final int WIDTH = 512;
    private static final int HEIGHT = 346;
    private static final Identifier SMOOTH_ID = Identifier.of(
            "monvhua", "dynamic/activity_bubble_preview/smooth");
    private static final Identifier PIXEL_ID = Identifier.of(
            "monvhua", "dynamic/activity_bubble_preview/pixel");
    private static NativeImageBackedTexture smooth;
    private static NativeImageBackedTexture pixel;

    private UiActivityBubblePreviewTexture() {
    }

    public static Identifier texture(UiActivityBubbleStyle style, MinecraftClient client) {
        if (client == null) {
            return null;
        }
        boolean pixelStyle = style == UiActivityBubbleStyle.PIXEL;
        NativeImageBackedTexture current = pixelStyle ? pixel : smooth;
        if (current == null) {
            NativeImage image = createImage(pixelStyle);
            current = new NativeImageBackedTexture(
                    () -> "monvhua activity bubble preview " + (pixelStyle ? "pixel" : "smooth"), image);
            current.setFilter(!pixelStyle, false);
            client.getTextureManager().registerTexture(pixelStyle ? PIXEL_ID : SMOOTH_ID, current);
            if (pixelStyle) {
                pixel = current;
            } else {
                smooth = current;
            }
        }
        return pixelStyle ? PIXEL_ID : SMOOTH_ID;
    }

    public static void clear(MinecraftClient client) {
        if (client == null) {
            smooth = null;
            pixel = null;
            return;
        }
        if (smooth != null) {
            client.getTextureManager().destroyTexture(SMOOTH_ID);
            smooth = null;
        }
        if (pixel != null) {
            client.getTextureManager().destroyTexture(PIXEL_ID);
            pixel = null;
        }
    }

    private static NativeImage createImage(boolean pixelStyle) {
        NativeImage image = new NativeImage(WIDTH, HEIGHT, false);
        for (int y = 0; y < HEIGHT; y++) {
            for (int x = 0; x < WIDTH; x++) {
                float u = (x + 0.5F) / WIDTH;
                float v = (y + 0.5F) / HEIGHT;
                float px = (u - 0.5F) * 0.92F;
                float py = (0.5F - v) * 0.62F;
                float distance = bubbleDistance(px, py);
                int argb;
                if (pixelStyle) {
                    int cellX = Math.min(27, (int) (u * 28.0F));
                    int cellY = Math.min(17, (int) (v * 18.0F));
                    argb = pixelFrameColor(pixelFrameKind(cellX, cellY));
                } else {
                    float aa = 1.4F / Math.min(WIDTH, HEIGHT);
                    float alpha = 1.0F - smoothstep(-aa, aa, distance);
                    if (alpha <= 0.001F) {
                        argb = 0;
                    } else {
                        float fill = 1.0F - smoothstep(-0.018F - aa, -0.018F + aa, distance);
                        int r = Math.round(9.0F + (249.0F - 9.0F) * fill);
                        int g = Math.round(9.0F + (250.0F - 9.0F) * fill);
                        int b = Math.round(10.0F + (247.0F - 10.0F) * fill);
                        int a = Math.round(alpha * 255.0F);
                        argb = (a << 24) | (r << 16) | (g << 8) | b;
                    }
                }
                image.setColorArgb(x, y, argb);
            }
        }
        return image;
    }

    /** Matches the world shader's 28x18 pixel bubble mask. */
    private static int pixelFrameKind(int x, int y) {
        if (y == 0) return x >= 8 && x <= 22 ? 2 : 0;
        if (y == 1) {
            if (x == 6 || x == 24) return 2;
            if (x == 7 || x == 23) return 3;
            if (x == 8 || x == 22) return 4;
            return x >= 9 && x <= 21 ? 1 : 0;
        }
        if (y == 2) {
            if (x == 5 || x == 25) return 2;
            if (x == 6 || x == 24) return 4;
            return x >= 7 && x <= 23 ? 1 : 0;
        }
        if (y == 3) {
            if (x == 4 || x == 26) return 2;
            if (x == 5 || x == 25) return 4;
            return x >= 6 && x <= 24 ? 1 : 0;
        }
        if (y == 4) {
            if (x == 4 || x == 26) return 3;
            return x >= 5 && x <= 25 ? 1 : 0;
        }
        if (y == 5) {
            if (x == 3 || x == 27) return 2;
            if (x == 4 || x == 26) return 4;
            return x >= 5 && x <= 25 ? 1 : 0;
        }
        if (y == 6 || y == 7) {
            if (x == 3) return 3;
            if (x == 27) return 2;
            return x >= 4 && x <= 26 ? 1 : 0;
        }
        if (y == 8) {
            if (x == 3) return 3;
            if (x == 26) return 4;
            if (x == 27) return 2;
            return x >= 4 && x <= 25 ? 1 : 0;
        }
        if (y == 9) {
            if (x == 3) return 2;
            if (x == 26) return 3;
            return x >= 4 && x <= 25 ? 1 : 0;
        }
        if (y == 10) {
            if (x == 3 || x == 26) return 2;
            if (x == 4 || x == 25) return 4;
            return x >= 5 && x <= 24 ? 1 : 0;
        }
        if (y == 11) {
            if (x == 3 || x == 25) return 2;
            if (x == 24) return 4;
            return x >= 4 && x <= 23 ? 1 : 0;
        }
        if (y == 12) {
            if (x == 2 || x == 6 || x == 24) return 2;
            if (x == 7 || x == 8 || x == 23) return 3;
            if (x == 9 || x == 22) return 4;
            return (x >= 3 && x <= 5) || (x >= 10 && x <= 21) ? 1 : 0;
        }
        if (y == 13) {
            if (x == 2) return 3;
            if (x == 5 || x == 6 || (x >= 8 && x <= 22)) return 2;
            return x == 3 || x == 4 ? 1 : 0;
        }
        if (y == 14) {
            if (x == 1 || x == 4) return 2;
            if (x == 2) return 4;
            return x == 3 ? 1 : 0;
        }
        if (y == 15) {
            if (x == 1) return 3;
            if (x == 3) return 2;
            return x == 2 ? 1 : 0;
        }
        if (y == 16) {
            if (x == 0 || x == 2) return 2;
            if (x == 1) return 4;
        }
        if (y == 17) return x <= 1 ? 2 : 0;
        return 0;
    }

    private static int pixelFrameColor(int kind) {
        return switch (kind) {
            case 1 -> 0xFFF9FAF7;
            case 2 -> 0xFF09090A;
            case 3 -> 0xFF696363;
            case 4 -> 0xFFA9A8A8;
            default -> 0;
        };
    }

    private static float bubbleDistance(float x, float y) {
        float body = roundedBoxDistance(x, y - 0.065F, 0.39F, 0.19F, 0.095F);
        float tail = triangleDistance(x, y,
                -0.235F, -0.105F,
                -0.325F, -0.275F,
                -0.055F, -0.115F) - 0.008F;
        return smoothUnion(body, tail, 0.022F);
    }

    private static float roundedBoxDistance(float x, float y,
                                            float halfWidth, float halfHeight, float radius) {
        float qx = Math.abs(x) - halfWidth + radius;
        float qy = Math.abs(y) - halfHeight + radius;
        float outside = (float) Math.sqrt(Math.max(qx, 0.0F) * Math.max(qx, 0.0F)
                + Math.max(qy, 0.0F) * Math.max(qy, 0.0F));
        return Math.min(Math.max(qx, qy), 0.0F) + outside - radius;
    }

    private static float triangleDistance(float px, float py,
                                          float ax, float ay, float bx, float by, float cx, float cy) {
        float distance = Math.min(segmentDistance(px, py, ax, ay, bx, by),
                Math.min(segmentDistance(px, py, bx, by, cx, cy),
                        segmentDistance(px, py, cx, cy, ax, ay)));
        float crossAB = (bx - ax) * (py - ay) - (by - ay) * (px - ax);
        float crossBC = (cx - bx) * (py - by) - (cy - by) * (px - bx);
        float crossCA = (ax - cx) * (py - cy) - (ay - cy) * (px - cx);
        boolean inside = (crossAB >= 0.0F && crossBC >= 0.0F && crossCA >= 0.0F)
                || (crossAB <= 0.0F && crossBC <= 0.0F && crossCA <= 0.0F);
        return inside ? -distance : distance;
    }

    private static float segmentDistance(float px, float py,
                                         float ax, float ay, float bx, float by) {
        float dx = bx - ax;
        float dy = by - ay;
        float lengthSquared = dx * dx + dy * dy;
        float t = lengthSquared <= 0.000001F
                ? 0.0F : Math.clamp(((px - ax) * dx + (py - ay) * dy) / lengthSquared, 0.0F, 1.0F);
        float qx = px - (ax + t * dx);
        float qy = py - (ay + t * dy);
        return (float) Math.sqrt(qx * qx + qy * qy);
    }

    private static float smoothUnion(float a, float b, float radius) {
        float h = Math.clamp(0.5F + 0.5F * (b - a) / radius, 0.0F, 1.0F);
        return (1.0F - h) * a + h * b - radius * h * (1.0F - h);
    }

    private static float smoothstep(float edge0, float edge1, float value) {
        float t = Math.clamp((value - edge0) / (edge1 - edge0), 0.0F, 1.0F);
        return t * t * (3.0F - 2.0F * t);
    }
}
